use smash::lib::LuaConst;

//COMMON
        //Ledge_const
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_EDGEHOG_ACTIVE: i32 = 0x20000140;
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_EDGE_INTANGIBLE: i32 = 0x20000141;
pub const MAX_PLAYERS: usize = 8;
pub const STICK_HISTORY_FRAMES: usize = 5; // or however many frames you're using
pub const IS_LATE_PIVOT: i32 = 0x004E;
pub const CAN_PERFECT_PIVOT: i32 = 0x004F;

pub const FIGHTER_INSTANCE_WORK_ID_FLAG_ALL_LAST_STOCK: i32 = 0x20000116; //Indicates all fighters are on their last stock
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_ALREADY_BOUNCED: i32 = 0x20000117; //Tracks if the ball has bounced at least once since being thrown
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_ASDI_START: i32 = 0x20000118;
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_AUTO_COUNTER: i32 = 496;
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_B_CHECK: i32 = 497; //Tracks if a fighter used a certain special move in the air
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_CAN_ADD: i32 = 498;
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_DAMAGED: i32 = 499;
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_DAMAGED_PREVENT: i32 = 500;
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_DID_MAX_JUMP_COUNT: i32 = 501;
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_FIGHTER_SPECIAL_STATE: i32 = 502;
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_FULL_SMASH_ATTACK: i32 = 503;
pub const FIGHTER_INSTANCE_WORK_ID_INT_GOT_HIT: i32 = 504; //Tracks if a player got hit during One-Hit mode
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_HITFLOW: i32 = 505;
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_IS_WAVEDASH: LuaConst = LuaConst::new(506);
pub const FIGHTER_INSTANCE_WORK_ID_INT_MASHING: i32 = 507;
pub const FIGHTER_INSTANCE_WORK_ID_INT_PARRIED: i32 = 508;
pub const FIGHTER_INSTANCE_WORK_ID_INT_PARRY_TIMER: i32 = 509;
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_READY_GO: i32 = 510; //Returns false for exactly one frame after is_ready_go becomes true, used to initiate certain events exactly once at the start of a match
pub const FIGHTER_INSTANCE_WORK_ID_INT_SHIELD_BREAK_TIMER: i32 = 511;
pub const FIGHTER_INSTANCE_WORK_ID_INT_SHIELD_EFFECT_TIMER: i32 = 512;
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_SHIELD_SPECIAL: i32 = 513;
pub const FIGHTER_INSTANCE_WORK_ID_INT_SPECIAL_ZOOM_EFFECT: i32 = 514;
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_USED_FS: i32 = 515; //Flags when you just used a Final Smash in Special Smash
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_WAVEDASH_DONE: i32 = 516;
pub const FIGHTER_INSTANCE_WORK_ID_INT_CLIFF_XLU_FRAME: i32 = 517;
pub const FIGHTER_INSTANCE_WORK_ID_INT_LANDING_FRAME: i32 = 518;
pub const FIGHTER_INSTANCE_WORK_ID_INT_CHARGE: LuaConst = LuaConst::new(0x100000BD);
pub const FIGHTER_INSTANCE_WORK_ID_INT_FRAME_COUNTER: LuaConst = LuaConst::new(0x100000BE);
pub const FIGHTER_INSTANCE_WORK_ID_INT_EFFECT_COUNTER: LuaConst = LuaConst::new(0x100000BF);
pub const FIGHTER_INSTANCE_WORK_ID_INT_SOUND_COUNTER: LuaConst = LuaConst::new(0x100000C0);
pub const FIGHTER_INSTANCE_WORK_ID_INT_CRITICAL_COUNTER: LuaConst = LuaConst::new(0x100000C1);
pub const FIGHTER_INSTANCE_WORK_ID_FLOAT_EFFECT_SCALE_MUL: LuaConst = LuaConst::new(0x4D);
pub const FIGHTER_INSTANCE_WORK_ID_FLOAT_BUTTON_ON_FRAME: LuaConst = LuaConst::new(0x4E);
pub const FIGHTER_INSTANCE_WORK_ID_FLOAT_STICK_DIRECTION: LuaConst = LuaConst::new(0x4F);
pub const FIGHTER_INSTANCE_WORK_ID_FLOAT_CSTICK_DIRECTION: LuaConst = LuaConst::new(0x50);
pub const FIGHTER_INSTANCE_WORK_ID_FLOAT_CRITICAL_ON_FRAME: LuaConst = LuaConst::new(0x51);
pub const FIGHTER_INSTANCE_WORK_ID_FLOAT_CHARGE_FRAME: LuaConst = LuaConst::new(0x642);
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_DISABLE_SPECIAL_HI: LuaConst = LuaConst::new(0x2000012C);
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_DISABLE_SPECIAL_LW: LuaConst = LuaConst::new(0x2000012D);
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_DISABLE_SPECIAL_N: LuaConst = LuaConst::new(0x2000012E);
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_DISABLE_SPECIAL_S: LuaConst = LuaConst::new(0x2000012F);
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_ENABLE_FLOAT: LuaConst = LuaConst::new(0x20000130);
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_CHECK_CRITICAL: LuaConst = LuaConst::new(0x20000131);
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_OMNI_FLOAT: LuaConst = LuaConst::new(0x20000132);
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_ATTACK_S4_IS_CHARGED: LuaConst = LuaConst::new(0x20000133);
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_ATTACK_HI4_IS_CHARGED: LuaConst = LuaConst::new(0x20000134);
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_ATTACK_LW4_IS_CHARGED: LuaConst = LuaConst::new(0x20000135);
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_ALLOT_STATUSES: LuaConst = LuaConst::new(0x20000136);
pub const FIGHTER_INSTANCE_WORK_ID_FLAG_ULTRA_ARMOR: LuaConst = LuaConst::new(0x20000137);
pub const FIGHTER_STATUS_WORK_FLAG_ULTRA_ARMOR: LuaConst = LuaConst::new(0x21000030);
pub const FIGHTER_STATUS_ATTACK_WORK_FLAG_CRITICAL: LuaConst = LuaConst::new(0x2100002A);
pub const FIGHTER_STATUS_GLIDE_WORK_FLOAT_GLIDE_FRAME: LuaConst = LuaConst::new(0x100000B);
pub const FIGHTER_STATUS_GLIDE_WORK_INT_PITCH_SE: LuaConst = LuaConst::new(0x11000007);
pub const FIGHTER_STATUS_GLIDE_WORK_INT_STOP_SE: LuaConst = LuaConst::new(0x11000008);
pub const FIGHTER_STATUS_JUMP_FLAG_ASCENSION_REVALI_ENABLE: LuaConst = LuaConst::new(0x21000018);
pub const FIGHTER_STATUS_ATTACK_FLAG_ENABLE_SPECIAL_N: LuaConst = LuaConst::new(0x21000023);
pub const FIGHTER_STATUS_ATTACK_FLAG_ENABLE_SPECIAL_S: LuaConst = LuaConst::new(0x21000024);
pub const FIGHTER_STATUS_ATTACK_FLAG_ENABLE_SPECIAL_HI: LuaConst = LuaConst::new(0x21000025);
pub const FIGHTER_STATUS_ATTACK_FLAG_ENABLE_SPECIAL_LW: LuaConst = LuaConst::new(0x21000026);
pub const FIGHTER_STATUS_FLOAT_WORK_FLAG_INHERIT_AERIAL: LuaConst = LuaConst::new(0x2100000D);
pub const FIGHTER_STATUS_FLOAT_WORK_FLAG_IS_FLOAT: LuaConst = LuaConst::new(0x2100000E);
pub const FIGHTER_STATUS_FLOAT_WORK_FLAG_TURN: LuaConst = LuaConst::new(0x2100000F);
pub const FIGHTER_STATUS_FLOAT_WORK_INT_TIME: LuaConst = LuaConst::new(0x11000006);
pub const FIGHTER_STATUS_FLOAT_WORK_INT_ENABLE_UNIQ: LuaConst = LuaConst::new(0x11000007);
pub const FIGHTER_STATUS_FLOAT_WORK_INT_MTRANS: LuaConst = LuaConst::new(0x11000008);
pub const FIGHTER_STATUS_FLOAT_WORK_FLOAT_ROT_Y: LuaConst = LuaConst::new(0x1000009);
pub const FIGHTER_STATUS_FLOAT_WORK_FLOAT_TURN_DIR: LuaConst = LuaConst::new(0x100000A);
pub const FIGHTER_STATUS_KIND_SPECIAL_GUARD: LuaConst = LuaConst::new(0x643);
pub const FIGHTER_STATUS_KIND_FLOAT: LuaConst = LuaConst::new(0x644);
pub const COLLISION_KIND_MASK_PARRY: LuaConst = LuaConst::new(0x80);



//DEDEDE
pub const FIGHTER_DEDEDE_STATUS_KIND_APPEAL_SPECIAL: LuaConst = LuaConst::new(0x110);
pub const FIGHTER_DEDEDE_INSTANCE_WORK_ID_INT_BGM_ID: LuaConst = LuaConst::new(0x100000C4);

//DEMON
pub const FIGHTER_DEMON_STATUS_ATTACK_WORK_FLAG_CRITICAL: LuaConst = LuaConst::new(0x2100002A);

//DIDDY
pub const FIGHTER_DIDDY_INSTANCE_WORK_ID_FLAG_BANANA_EXIST: LuaConst = LuaConst::new(0x200000E2);
pub const FIGHTER_DIDDY_INSTANCE_WORK_ID_FLAG_SPECIAL_LW_LAUGH_TRIGGER: LuaConst = LuaConst::new(0x200000E4);

//DONKEY
pub const FIGHTER_DONKEY_INSTANCE_WORK_ID_FLAG_APPEAL_SPECIAL: LuaConst = LuaConst::new(0x200000E1);
pub const FIGHTER_DONKEY_STATUS_KIND_SPECIAL_HI2 : LuaConst = LuaConst::new(0x1D3);


//LINK
pub const FIGHTER_LINK_INSTANCE_WORK_ID_FLAG_URBOSA_FURY: LuaConst = LuaConst::new(0x200000E9);
pub const FIGHTER_LINK_INSTANCE_WORK_ID_FLAG_SPIN_ATTACK_CAN_FALL: LuaConst = LuaConst::new(0x200000EA);
pub const FIGHTER_LINK_INSTANCE_WORK_ID_FLAG_PICK_ITEM: LuaConst = LuaConst::new(0x200000EB);
pub const FIGHTER_LINK_INSTANCE_WORK_ID_FLAG_BOMB_FUSED: LuaConst = LuaConst::new(0x200000EC);
pub const FIGHTER_LINK_INSTANCE_WORK_ID_FLAG_CAN_ASCEND: LuaConst = LuaConst::new(0x200000ED);
pub const FIGHTER_LINK_INSTANCE_WORK_ID_INT_FUSE_ITEM_ID: LuaConst = LuaConst::new(0x100000C6);
pub const FIGHTER_LINK_INSTANCE_WORK_ID_INT_TEAM_NO: LuaConst = LuaConst::new(0x100000C7);
pub const FIGHTER_LINK_INSTANCE_WORK_ID_INT_CURRENT_ARROW_FUSE: LuaConst = LuaConst::new(0x100000C8);
pub const FIGHTER_LINK_INSTANCE_WORK_ID_INT_CURRENT_BOOMERANG_FUSE: LuaConst = LuaConst::new(0x100000C9);
pub const FIGHTER_LINK_INSTANCE_WORK_ID_INT_CURRENT_BOOMERANG_FUSE_ID: LuaConst = LuaConst::new(0x100000CA);
pub const FIGHTER_LINK_INSTANCE_WORK_ID_INT_CURRENT_ASCEND_FRAME: LuaConst = LuaConst::new(0x100000CB);
pub const FIGHTER_LINK_INSTANCE_WORK_ID_INT_JUMP_BUTTON_ON_FRAME: LuaConst = LuaConst::new(0x100000CC);
pub const FIGHTER_LINK_INSTANCE_WORK_ID_FLOAT_ASCEND_START_Y: LuaConst = LuaConst::new(0x100000CB);
pub const FIGHTER_LINK_INSTANCE_WORK_ID_FLOAT_ASCEND_TARGET_Y: LuaConst = LuaConst::new(0x100000CC);
pub const FIGHTER_LINK_STATUS_KIND_ATTACK_DASH_BOUND: LuaConst = LuaConst::new(0x1E9);
pub const FIGHTER_LINK_STATUS_KIND_REVALI_GLIDE: LuaConst = LuaConst::new(0x1EA);
pub const FIGHTER_LINK_STATUS_KIND_REVALI_GLIDE_TURN: LuaConst = LuaConst::new(0x1EB);
pub const FIGHTER_LINK_STATUS_KIND_REVALI_GLIDE_DROP: LuaConst = LuaConst::new(0x1EC);
pub const FIGHTER_LINK_STATUS_KIND_REVALI_GLIDE_LANDING: LuaConst = LuaConst::new(0x1ED);
pub const FIGHTER_LINK_STATUS_KIND_ASCEND_START: LuaConst = LuaConst::new(0x1EE);
pub const FIGHTER_LINK_STATUS_KIND_ASCEND: LuaConst = LuaConst::new(0x1EF);
pub const FIGHTER_LINK_STATUS_KIND_ASCEND_END: LuaConst = LuaConst::new(0x1F0);
pub const FIGHTER_LINK_STATUS_KIND_ASCEND_JUMP_GROUND: LuaConst = LuaConst::new(0x1F1);
pub const FIGHTER_LINK_STATUS_KIND_ASCEND_JUMP_GROUND_END: LuaConst = LuaConst::new(0x1F2);
pub const FIGHTER_LINK_GENERATE_ARTICLE_CLAWSHOT: LuaConst = LuaConst::new(0x9);
pub const FIGHTER_LINK_GENERATE_ARTICLE_CLAWSHOT_HAND: LuaConst = LuaConst::new(0xA);
pub const WN_LINK_BOWARROW_INSTANCE_WORK_ID_INT_FUSE_ITEM_KIND: LuaConst = LuaConst::new(0x1000000E);
pub const WN_LINK_BOWARROW_INSTANCE_WORK_ID_INT_FUSE_ITEM_SPECIAL_FLAG: LuaConst = LuaConst::new(0x1000000F);
pub const WN_LINK_BOWARROW_INSTANCE_WORK_ID_INT_FUSE_ITEM_SPECIAL_STATUS: LuaConst = LuaConst::new(0x10000010);
pub const WN_LINK_BOWARROW_INSTANCE_WORK_ID_INT_FUSE_ITEM_ID: LuaConst = LuaConst::new(0x10000011);
pub const WN_LINK_BOWARROW_INSTANCE_WORK_ID_FLAG_ITEM_FUSED: LuaConst = LuaConst::new(0x20000009);
pub const WN_LINK_BOWARROW_INSTANCE_WORK_ID_FLAG_FUSE_REFLECT: LuaConst = LuaConst::new(0x2000000A);
pub const WN_LINK_BOWARROW_INSTANCE_WORK_ID_FLAG_FUSE_DEDEDE_SWALLOW: LuaConst = LuaConst::new(0x2000000B);
pub const WN_LINK_BOOMERANG_INSTANCE_WORK_ID_INT_FUSE_ITEM_KIND: LuaConst = LuaConst::new(0x1000000C);
pub const WN_LINK_BOOMERANG_INSTANCE_WORK_ID_INT_FUSE_ITEM_SPECIAL_STATUS: LuaConst = LuaConst::new(0x1000000D);
pub const WN_LINK_BOOMERANG_INSTANCE_WORK_ID_INT_FUSE_ITEM_ID: LuaConst = LuaConst::new(0x1000000E);
pub const WN_LINK_BOOMERANG_INSTANCE_WORK_ID_FLAG_ITEM_FUSED: LuaConst = LuaConst::new(0x2000000E);
pub const WN_LINK_BOOMERANG_INSTANCE_WORK_ID_FLAG_FUSE_REFLECT: LuaConst = LuaConst::new(0x2000000F);

//KIRBY
pub const FIGHTER_KIRBY_STATUS_KIND_SPECIAL_HI_H: LuaConst = LuaConst::new(0x3E6);
pub const FIGHTER_KIRBY_INSTANCE_WORK_ID_INT_CURRENT_ARROW_FUSE:  LuaConst = LuaConst::new(0x1000010B);
pub const FIGHTER_KIRBY_INSTANCE_WORK_ID_INT_TEAM_NO: LuaConst = LuaConst::new(0x1000010C);
pub const FIGHTER_KIRBY_STATUS_SPECIAL_HI_FLAG_CANCEL: LuaConst = LuaConst::new(0x2100001E);

//KNUCKLES
pub const THROW_HI_FRAME_FALL: f32 = 30.0;
pub const THROW_HI_FRAME_LAND: f32 = 39.0;

//MARIO
pub const FIGHTER_MARIO_STATUS_SPECIAL_N_FLAG_SPECIAL_N_GIANT_FIREBALL: LuaConst = LuaConst::new(0x2100000E);
pub const FIGHTER_MARIO_INSTANCE_WORK_ID_INT_SPECIAL_BUTTON_ON_FRAME: LuaConst = LuaConst::new(0x100000BF);

//METAKNIGHT
pub const FIGHTER_METAKNIGHT_INSTANCE_WORK_ID_FLAG_DISABLE_AIR_SPECIAL_N: LuaConst = LuaConst::new(0x200000E6);
pub const FIGHTER_METAKNIGHT_INSTANCE_WORK_ID_FLAG_DISABLE_AIR_SPECIAL_S: LuaConst = LuaConst::new(0x200000E7);
pub const FIGHTER_METAKNIGHT_INSTANCE_WORK_ID_FLAG_DISABLE_AIR_SPECIAL_HI: LuaConst = LuaConst::new(0x200000E8);
pub const FIGHTER_METAKNIGHT_INSTANCE_WORK_ID_FLAG_DISABLE_AIR_SPECIAL_LW: LuaConst = LuaConst::new(0x200000E9);
pub const FIGHTER_METAKNIGHT_STATUS_KIND_SPECIAL_GUARD: LuaConst = LuaConst::new(0x1F0);
pub const FIGHTER_METAKNIGHT_GENERATE_ARTICLE_GALAXIA_BEAM: LuaConst = LuaConst::new(0x3);
pub const FIGHTER_METAKNIGHT_INSTANCE_WORK_ID_FLAG_AIR_SPECIAL_GUARD: LuaConst = LuaConst::new(0x200000E5);
pub const FIGHTER_METAKNIGHT_INSTANCE_WORK_ID_FLAG_META_POWER: LuaConst = LuaConst::new(0x200000EA);  
pub const WEAPON_METAKNIGHT_GALAXIA_BEAM_STATUS_KIND_SHOOT: LuaConst = LuaConst::new(0x0);
pub const WEAPON_METAKNIGHT_GALAXIA_BEAM_STATUS_KIND_END: LuaConst = LuaConst::new(0x1);
pub const WEAPON_METAKNIGHT_GALAXIA_BEAM_INSTANCE_WORK_ID_FLOAT_ANGLE: LuaConst = LuaConst::new(0x1);
pub const WEAPON_METAKNIGHT_GALAXIA_BEAM_INSTANCE_WORK_ID_FLOAT_ROT: LuaConst = LuaConst::new(0x2);

//PALUTENA
pub const FIGHTER_PALUTENA_INSTANCE_WORK_ID_FLAG_DIVINE_POWER: LuaConst = LuaConst::new(0x200000E9); 

//PIT
pub const FIGHTER_PIT_STATUS_KIND_SPECIAL_HI_FLY: LuaConst = LuaConst::new(0x1D3);
pub const FIGHTER_PIT_STATUS_KIND_SPECIAL_HI_FLY_END: LuaConst = LuaConst::new(0x1F0);
pub const FIGHTER_PIT_STATUS_SPECIAL_HI_FLY_WORK_INT_TIME: LuaConst = LuaConst::new(0x1000011);
pub const FIGHTER_PIT_STATUS_SPECIAL_HI_FLY_WORK_INT_LAND_TIME: LuaConst = LuaConst::new(0x1000012);
pub const FIGHTER_PIT_STATUS_SPECIAL_HI_FLY_WORK_INT_START_SE: LuaConst = LuaConst::new(0x1000013);
pub const FIGHTER_PIT_STATUS_SPECIAL_HI_FLY_WORK_INT_START_SE_COUNTER: LuaConst = LuaConst::new(0x1000014);
pub const FIGHTER_PIT_STATUS_SPECIAL_HI_FLY_WORK_FLAG_BURN: LuaConst = LuaConst::new(0x1000015);
pub const FIGHTER_PIT_INSTANCE_WORK_ID_FLOAT_SPECIAL_HI_FLY_POWER: LuaConst = LuaConst::new(0x4C);

//PLIZARDON
pub const FIGHTER_PLIZARDON_STATUS_KIND_SPECIAL_HI2: LuaConst = LuaConst::new(0x1DB);
pub const FIGHTER_PLIZARDON_STATUS_KIND_SPECIAL_HI2_LANDING: LuaConst = LuaConst::new(0x1D3);
pub const FIGHTER_PLIZARDON_STATUS_KIND_SPECIAL_GUARD: LuaConst = LuaConst::new(0x1D2);
pub const FIGHTER_PLIZARDON_STATUS_ROCKSTONE_WORK_INT_INTERVAL_FRAME_COUNT: LuaConst = LuaConst::new(0x11000011);
pub const FIGHTER_PLIZARDON_STATUS_ROCKSTONE_FLAG_GENE_ROCK: LuaConst = LuaConst::new(0x21000010);
pub const FIGHTER_PLIZARDON_STATUS_ATTACK_WORK_FLAG_CRITICAL: LuaConst = LuaConst::new(0x200000E7);
pub const FIGHTER_PLIZARDON_GENERATE_ARTICLE_ROCK: LuaConst = LuaConst::new(0x3);
pub const FIGHTER_PLIZARDON_GENERATE_ARTICLE_ROCKSTONE: LuaConst = LuaConst::new(0x4);
pub const WEAPON_PLIZARDON_ROCK_STATUS_KIND_START: LuaConst = LuaConst::new(0x0);
pub const WEAPON_PLIZARDON_ROCK_INSTANCE_WORK_ID_FLAG_BREAK: LuaConst = LuaConst::new(0x2000000B);
pub const WEAPON_PLIZARDON_ROCK_INSTANCE_WORK_ID_INT_SPAWN_COOLDOWN: LuaConst = LuaConst::new(0x1000000A);
pub const WEAPON_PLIZARDON_ROCK_INSTANCE_WORK_ID_INT_STONES_MAX: LuaConst = LuaConst::new(0x10000004);
pub const WEAPON_PLIZARDON_ROCK_INSTANCE_WORK_ID_INT_STONES_REMAIN: LuaConst = LuaConst::new(0x10000005);
pub const WEAPON_PLIZARDON_ROCKSTONE_STATUS_KIND_START: LuaConst = LuaConst::new(0x0);
pub const WEAPON_PLIZARDON_ROCKSTONE_STATUS_KIND_MOVE: LuaConst = LuaConst::new(0x2);
pub const WEAPON_PLIZARDON_ROCKSTONE_INSTANCE_WORK_ID_FLOAT_ANGLE: LuaConst = LuaConst::new(0x10000009);
pub const WEAPON_PLIZARDON_ROCKSTONE_INSTANCE_WORK_ID_FLOAT_ROT: LuaConst = LuaConst::new(0x1000000B);

//PZENIGAME
pub const FIGHTER_PZENIGAME_STATUS_KIND_SPECIAL_GUARD: i32 = 0x1D3;

//PFUSHIGISOU
pub const FIGHTER_PFUSHIGISOU_STATUS_KIND_SPECIAL_GUARD_SHOOT: LuaConst = LuaConst::new(0x1D3);
pub const FIGHTER_PFUSHIGISOU_STATUS_KIND_SPECIAL_GUARD_END: LuaConst = LuaConst::new(0x1DA);

//LUCARIO
pub const FIGHTER_LUCARIO_INSTANCE_WORK_ID_FLAG_ENABLE_SPECIAL_HI: LuaConst = LuaConst::new(0x200000E3);
pub const FIGHTER_LUCARIO_INSTANCE_WORK_ID_FLAG_DISABLE_SPECIAL_HI: LuaConst = LuaConst::new(0x200000E4);

//LUCAS & CLAUS
pub const FIGHTER_LUCAS_STATUS_ATTACK_WORK_FLAG_CRITICAL: LuaConst = LuaConst::new(0x21000010);

//LUCINA
pub const FIGHTER_LUCINA_STATUS_KIND_SPECIAL_LW_HIT2: LuaConst = LuaConst::new(0x1EF);
pub const FIGHTER_LUCINA_STATUS_SPECIAL_LW_FLAG_ACTIVATE_SPECIAL_LW_HIT2: LuaConst = LuaConst::new(0x2100001F);

//LUIGI
pub const FIGHTER_LUIGI_INSTANCE_WORK_ID_INT_SPECIAL_S_PULSE_EFFECT_HANDLE: LuaConst = LuaConst::new(0x100000C3);
pub const FIGHTER_LUIGI_INSTANCE_WORK_ID_INT_SPECIAL_S_SMOKE_EFFECT_HANDLE: LuaConst = LuaConst::new(0x100000C4);

//RYU
pub const FIGHTER_RYU_STATUS_KIND_KAMEHAMEHA_START: i32 = 0x202;
pub const FIGHTER_RYU_STATUS_KIND_KAMEHAMEHA_CHARGE: i32 = 0x203;
pub const FIGHTER_RYU_STATUS_KIND_KAMEHAMEHA_FIRE: i32 = 0x204;
pub const FIGHTER_RYU_STATUS_WORK_ID_KAMEHAMEHA_FLOAT_CHARGE_TIME: i32 = 0x2100001C;

//SHIZUE
pub const FIGHTER_SHIZUE_INSTANCE_WORK_ID_INT_SHOT_KIND: LuaConst = LuaConst::new(0x100000D2); 
pub const FIGHTER_SHIZUE_INSTANCE_WORK_ID_FLAG_RANDOM_SHOT: LuaConst = LuaConst::new(0x200000F1);

//SIMON & RICHTER
pub const FIGHTER_SIMON_INSTANCE_WORK_ID_FLAG_DISABLE_SPECIAL_HI: LuaConst = LuaConst::new(0x200000F7);

//TRAIL
pub const FIGHTER_TRAIL_INSTANCE_WORK_ID_FLAG_DISABLE_AIR_SPECIAL_S: LuaConst = LuaConst::new(0x200000E6);
pub const FIGHTER_TRAIL_INSTANCE_WORK_ID_FLAG_DISABLE_AIR_SPECIAL_HI: LuaConst = LuaConst::new(0x200000E7);

//WOLF
pub const FIGHTER_WOLF_STATUS_KIND_SPECIAL_S_RUSH: LuaConst = LuaConst::new(0x1EA);
pub const FIGHTER_WOLF_STATUS_KIND_SPECIAL_S_END: LuaConst = LuaConst::new(0x1EB);


pub mod globals {
    // 0x1
    pub const FIGHTER_KIND:          i32 = 0x2;
    pub const OBJECT_ID:             i32 = 0x3;
    // 0x4
    pub const MODULE_ACCESSOR:       i32 = 0x5;
    // 0x6
    pub const INIT_STATUS_FUNC:      i32 = 0x7;
    pub const IS_STOPPING:           i32 = 0x8;
    pub const STATUS_KIND_INTERRUPT: i32 = 0x9;
    pub const PREV_STATUS_KIND:      i32 = 0xA;
    pub const STATUS_KIND:           i32 = 0xB;
    pub const STATUS_COUNT:          i32 = 0xC;
    // 0xD
    pub const CURRENT_FRAME:         i32 = 0xE;
    pub const CURRENT_FRAME2:        i32 = 0xF;
    // 0x10
    // 0x11 func ptr
    // 0x12
    pub const SUB_STATUS3:           i32 = 0x13;
    pub const SUB_STATUS2:           i32 = 0x14;
    pub const SUB_STATUS:            i32 = 0x15;
    pub const SITUATION_KIND:        i32 = 0x16;
    pub const PREV_SITUATION_KIND:   i32 = 0x17;
    pub const PREV_STATUS_FRAME:     i32 = 0x18;
    // 0x19
    pub const STICK_X:               i32 = 0x1A;
    pub const STICK_Y:               i32 = 0x1B;
    pub const FLICK_X:               i32 = 0x1C;
    pub const FLICK_Y:               i32 = 0x1D;
    pub const FLICK_Y_DIR:           i32 = 0x1E;
    pub const PAD_FLAG:              i32 = 0x1F;
    pub const CMD_CAT1:              i32 = 0x20;
    pub const CMD_CAT2:              i32 = 0x21;
    pub const CMD_CAT3:              i32 = 0x22;
    pub const CMD_CAT4:              i32 = 0x23;
    // 0x24
    // 0x25
    // 0x26
    // 0x27
    // 0x28 some substatus
    pub const DASH_CALLBACK:         i32 = 0x29;
    // 0x2A
    pub const CUSTOM_ROUTINE:        i32 = 0x2B;
    // 0x2C
    // 0x2D
    // 0x2E
    // 0x2F
    // 0x30
    // 0x31
    // 0x32 some substatus
    pub const USE_SPECIAL_N_CALLBACK: i32 = 0x38;
    pub const USE_SPECIAL_S_CALLBACK: i32 = 0x39;
    pub const USE_SPECIAL_HI_CALLBACK: i32 = 0x3A;
    pub const USE_SPECIAL_LW_CALLBACK: i32 = 0x3B;
    pub const CHECK_SPECIAL_COMMAND: i32 = 0x3C;
    pub const WAZA_CUSTOMIZE_CONTROL: i32 = 0x3D;
    pub const STATUS_CHANGE_CALLBACK: i32 = 0x3E;
    pub const DAMAGE_MOTION_KIND_CALLBACK: i32 = 0x42;
    pub const DASH_POST_TRANSITION_CALLBACK: i32 = 0x57;
    

}
